alter table if exists Book drop constraint if exists FKl8lxbjh0wptss27owag6it4i7;
alter table if exists Book drop constraint if exists FKrc4aujt4u7vihi7kovrbbtxsv;
alter table if exists CD drop constraint if exists FKaytv0uvt7n00ea6i2dnw4o78v;
alter table if exists t_items drop constraint if exists FKr3152tukbog585dik5qwonldg;
alter table if exists t_purchase_order_lines drop constraint if exists FKf51l5n972qc282ubbv97c1kfa;
alter table if exists t_purchase_order_lines drop constraint if exists FKbjsagtstxdmdm55cxqvbxkaji;
alter table if exists t_purchase_orders drop constraint if exists FK93wd2w995ng3vyj51y4fur1hg;
alter table if exists t_tracks drop constraint if exists FKd2cxlowirxhlmf3s87rc8jcvf;
drop table if exists Book cascade;
drop table if exists CD cascade;
drop table if exists t_artists cascade;
drop table if exists t_customers cascade;
drop table if exists t_items cascade;
drop table if exists t_publishers cascade;
drop table if exists t_purchase_order_lines cascade;
drop table if exists t_purchase_orders cascade;
drop table if exists t_tracks cascade;
drop sequence if exists hibernate_sequence;
